# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-26 06:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dongzip', '0002_remove_profile_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='profile_image',
            field=models.ImageField(null=True, upload_to='uploaded/user_profile/%y/%m/%d'),
        ),
        migrations.AddField(
            model_name='school',
            name='logo_image',
            field=models.ImageField(null=True, upload_to='uploaded/school_profile/%y/%m/%d'),
        ),
        migrations.AddField(
            model_name='society',
            name='background_image',
            field=models.ImageField(null=True, upload_to='uploaded/society_profile/%y/%m/%d'),
        ),
        migrations.AddField(
            model_name='society',
            name='logo_image',
            field=models.ImageField(null=True, upload_to='uploaded/society_profile/%y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='event',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='nickname',
            field=models.CharField(max_length=128),
        ),
    ]
