# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-10 07:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dongzip', '0010_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='society',
        ),
        migrations.AddField(
            model_name='society',
            name='society',
            field=models.ManyToManyField(blank=True, to='dongzip.Category'),
        ),
    ]
