# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-26 07:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dongzip', '0003_auto_20170126_1558'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='nickname',
            field=models.CharField(max_length=128),
        ),
    ]
