# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-26 07:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dongzip', '0004_auto_20170126_1603'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='nickname',
        ),
    ]
