# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-26 07:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dongzip', '0005_remove_profile_nickname'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='nickname',
            field=models.CharField(default='지방', max_length=128),
            preserve_default=False,
        ),
    ]
