# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-08 10:51
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dongzip', '0007_auto_20170126_1630'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='school',
            name='logo_image',
        ),
        migrations.AddField(
            model_name='school',
            name='point',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='uploaded/user_profile/'),
        ),
        migrations.AlterField(
            model_name='society',
            name='background_image',
            field=models.ImageField(blank=True, null=True, upload_to='uploaded/society_profile/'),
        ),
        migrations.AlterField(
            model_name='society',
            name='logo_image',
            field=models.ImageField(blank=True, null=True, upload_to='uploaded/society_profile/'),
        ),
    ]
