# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-14 06:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dongzip', '0012_auto_20170210_1639'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='url_name',
            field=models.CharField(default='', max_length=32),
            preserve_default=False,
        ),
    ]
