# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-14 10:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dongzip', '0013_category_url_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='society',
            name='address',
        ),
    ]
