# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-14 11:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dongzip', '0014_remove_society_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='society',
            name='member_number',
        ),
    ]
