# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-14 12:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dongzip', '0015_remove_society_member_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='favorite_society',
            field=models.ForeignKey(default=6, on_delete=django.db.models.deletion.CASCADE, to='dongzip.Society'),
            preserve_default=False,
        ),
    ]
