# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-15 09:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dongzip', '0016_profile_favorite_society'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='favorite_society',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='dongzip.Society'),
        ),
    ]
