# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-15 14:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dongzip', '0019_auto_20170215_1859'),
    ]

    operations = [
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('power', models.IntegerField(default=0)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='society',
            name='users',
        ),
        migrations.AddField(
            model_name='membership',
            name='society',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dongzip.Society'),
        ),
        migrations.AddField(
            model_name='membership',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dongzip.Profile'),
        ),
        migrations.AddField(
            model_name='society',
            name='users',
            field=models.ManyToManyField(through='dongzip.Membership', to='dongzip.Profile'),
        ),
    ]
