# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-15 13:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dongzip', '0019_auto_20170215_1859'),
        ('dongzip', '0017_remove_profile_favorite_society'),
    ]

    operations = [
    ]
