# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-15 13:43
from __future__ import unicode_literals

from django.db import migrations, models
import dongzip.models


class Migration(migrations.Migration):

    dependencies = [
        ('dongzip', '0020_merge_20170215_2243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='tel_number',
            field=models.CharField(max_length=32, validators=[dongzip.models.tel_number_validator]),
        ),
    ]
