# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-15 13:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dongzip', '0021_auto_20170215_2243'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='favorite_society',
            field=models.ManyToManyField(blank=True, null=True, to='dongzip.Society'),
        ),
    ]
