# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-15 16:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dongzip', '0022_profile_favorite_society'),
        ('dongzip', '0020_auto_20170215_2331'),
    ]

    operations = [
    ]
