# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-15 17:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dongzip', '0023_merge_20170216_0107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='favorite_society',
            field=models.ManyToManyField(to='dongzip.Society'),
        ),
    ]
