# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-07 09:26
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dongzip', '0007_auto_20170126_1630'),
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolLocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('point', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('school', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='dongzip.School')),
            ],
        ),
    ]
